config/routes.rb
Rails.application.routes.draw do
  resources :ticket_attachments
  resources :tickets

    resources :tickets do
    collection do
      match 'search' => 'tickets#search', via: [:get, :post], as: :search
    end
  end

  root 'tickets#index'

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
    has_many :ticket_attachments
   accepts_nested_attributes_for :ticket_attachments
end

app/models/ticket_attachment.rb
class TicketAttachment < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  belongs_to :ticket
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :set_global_search_variable

  def set_global_search_variable
    @q = Ticket.search(params[:q])
  end
end

app/controllers/ticket_attachments_controller.rb
class TicketAttachmentsController < ApplicationController
  before_action :set_ticket_attachment, only: [:show, :edit, :update, :destroy]

  # GET /ticket_attachments
  # GET /ticket_attachments.json
  def index
    @ticket_attachments = TicketAttachment.all
  end

  # GET /ticket_attachments/1
  # GET /ticket_attachments/1.json
  def show
  end

  # GET /ticket_attachments/new
  def new
    @ticket_attachment = TicketAttachment.new
  end

  # GET /ticket_attachments/1/edit
  def edit
  end

  # POST /ticket_attachments
  # POST /ticket_attachments.json
  def create
    @ticket_attachment = TicketAttachment.new(ticket_attachment_params)

    respond_to do |format|
      if @ticket_attachment.save
        format.html { redirect_to @ticket_attachment, notice: 'Ticket attachment was successfully created.' }
        format.json { render :show, status: :created, location: @ticket_attachment }
      else
        format.html { render :new }
        format.json { render json: @ticket_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ticket_attachments/1
  # PATCH/PUT /ticket_attachments/1.json
  def update
    respond_to do |format|
      if @ticket_attachment.update(ticket_attachment_params)
        format.html { redirect_to @ticket_attachment, notice: 'Ticket attachment was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket_attachment }
      else
        format.html { render :edit }
        format.json { render json: @ticket_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ticket_attachments/1
  # DELETE /ticket_attachments/1.json
  def destroy
    @ticket_attachment.destroy
    respond_to do |format|
      format.html { redirect_to ticket_attachments_url, notice: 'Ticket attachment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket_attachment
      @ticket_attachment = TicketAttachment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_attachment_params
      params.require(:ticket_attachment).permit(:ticket_id, :image)
    end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  # GET /tickets
  # GET /tickets.json
  def index
    # @tickets = Ticket.all
    @q = Ticket.ransack(params[:q])
    @tickets = @q.result(distinct: true).paginate(:page => params[:page], :per_page => 10).order('created_at DESC')
  end

  def search
    index
    render :index
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
    @ticket_attachments = @ticket.ticket_attachments.all
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
    @ticket_attachment = @ticket.ticket_attachments.build
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)

    respond_to do |format|
      if @ticket.save
         params[:ticket_attachments]['image'].each do |i|
          @ticket_attachment = @ticket.ticket_attachments.create!(:image => i)
       end
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:from, :subject, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ticket_attachments_helper.rb
module TicketAttachmentsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tickets</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="ui left vertical menu sidebar">
    <a class="item">
      Item 1
    </a>
    <a class="item">
      Item 2
    </a>
    <a class="item">
      Item 3
    </a>
  </div>
<%= yield %>

</body>
</html>

app/views/ticket_attachments/_form.html.erb
<%= form_for(@ticket_attachment) do |f| %>
  <% if @ticket_attachment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket_attachment.errors.count, "error") %> prohibited this ticket_attachment from being saved:</h2>

      <ul>
      <% @ticket_attachment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ticket_id %><br>
    <%= f.number_field :ticket_id %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ticket_attachments/edit.html.erb
<h1>Editing Ticket Attachment</h1>

<%= render 'form' %>

<%= link_to 'Show', @ticket_attachment %> |
<%= link_to 'Back', ticket_attachments_path %>

app/views/ticket_attachments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ticket Attachments</h1>

<table>
  <thead>
    <tr>
      <th>Ticket</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ticket_attachments.each do |ticket_attachment| %>
      <tr>
        <td><%= ticket_attachment.ticket_id %></td>
        <td><%= ticket_attachment.image %></td>
        <td><%= link_to 'Show', ticket_attachment %></td>
        <td><%= link_to 'Edit', edit_ticket_attachment_path(ticket_attachment) %></td>
        <td><%= link_to 'Destroy', ticket_attachment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ticket attachment', new_ticket_attachment_path %>

app/views/ticket_attachments/new.html.erb
<h1>New Ticket Attachment</h1>

<%= render 'form' %>

<%= link_to 'Back', ticket_attachments_path %>

app/views/ticket_attachments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ticket:</strong>
  <%= @ticket_attachment.ticket_id %>
</p>

<p>
  <strong>Image:</strong>
  <%= @ticket_attachment.image %>
</p>

<%= link_to 'Edit', edit_ticket_attachment_path(@ticket_attachment) %> |
<%= link_to 'Back', ticket_attachments_path %>

app/views/tickets/_form.html.erb
<div class="ui form">
  <%= form_for(@ticket) do |f| %>
    <% if @ticket.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

        <ul>
        <% @ticket.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <h3><%= f.label :from, "From email address" %></h3>
      <%= f.text_field :from %>
    </div>
    <div class="field">
      <h3><%= f.label :subject, "Subject" %></h3>
      <%= f.text_field :subject %>
    </div>
    <div class="field">
      <h3><%= f.label :content, "Content" %></h3>
        <%= f.text_area :content, :class => "tinymce" %>
      <%= tinymce %>
    </div>
    <div class="ui segment">
      <%= f.fields_for :ticket_attachments do |p| %>
          <h3><label><i class="attach icon"></i>Attach file(s)</label></h3>
        <%= p.file_field :image, value: "file", class: 'ui basic blue button', :multiple => true, name: "ticket_attachments[image][]" %>
      <% end %>
      
    </div>


    <div class="ui buttons">
      <button class="ui basic blue button" type="submit">
        <i class="icon send outline"></i>
        Send ticket
      </button>
    </div>
  <% end %>

</div>


<script type="text/javascript">
  tinyMCE.init({
    selector: 'textarea.content'
  });
</script>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form' %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<p id="notice"><%= notice %></p>

<div class="ui container">

  <div class="ui grid">
    <div class="ten wide column">
      <% if @tickets.present? %>
        <h1>Listing Tickets (<%= @q.result(distinct: true).length %>)</h1>
      <% else %>
        <h1>0 tickets containing '<%= params[:search] %>'  </h1>
        <%= link_to 'Back to tickets', tickets_path %>
      <% end%>
    </div>

    <!-- search form -->
    <div class="six wide column">
      <div class="ui fluid category search">
        <%= search_form_for @q, url: search_tickets_path,
                        html: { method: :post } do |f| %>
          <div class="ui icon input">
            <%= f.search_field :subject_or_from_cont, :class => "prompt", :type => "search", :placeholder => "Enter Search..." %>
            <i class="search icon"></i>
          </div>
        <% end %>
        <div class="results"></div>
      </div>
    </div>
  </div>


<!--   list_ticket -->
  <div class="ui divided items" id="index_ticket">
    <% @tickets.each do |ticket| %>
      <div class="item">
        <div class="content">
          <div class="header"><%= link_to ticket.subject, ticket %></div>
          <div class="description">
            <p>#<%=ticket.id%> created by <a><%= ticket.from %></a> at <%= ticket.created_at %></p>
          </div>
          <%= link_to 'Show', ticket %>
          <%= link_to 'Edit', edit_ticket_path(ticket) %>
          <%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      </div> 
    <% end %>
  </div>
<%= will_paginate %>

  <%= link_to 'New Ticket', new_ticket_path %>
</div>
<!-- 
<div>
<script>

  var src_str = $("#index_ticket").html();
  var term = "<%= @q %>";
  term = term.replace(/(\s+)/,"(<[^>]+>)*$1(<[^>]+>)*");
  var pattern = new RegExp("("+term+")", "gi");

  src_str = src_str.replace(pattern, "<mark>$1</mark>");
  src_str = src_str.replace(/(<mark>[^<>]*)((<[^>]+>)+)([^<>]*<\/mark>)/,"$1</mark>$2<mark>$4");

  $("#index_ticket").html(src_str);
  
</script>
</div>
 -->

app/views/tickets/new.html.erb
<div class="ui container">
  <h1>New Ticket</h1>

  <%= render 'form' %>

  <%= link_to 'Back', tickets_path %>
</div>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>
<div class="ui container">

  
  <h2><%= @ticket.subject %></h2>
  
 
  <p style="font-size: 1.2em;">By <%= @ticket.from %> on <%= @ticket.created_at %></p>
  <p>Ticket number <%= @ticket.id %></p> 
  <span>
    Action
   <div class="ui floating dropdown labeled search icon button">
      <span class="text">Select action</span>
      <div class="menu">
        <div class="item">1</div>
        <div class="item">2</div>
        <div class="item">3</div>
        <div class="item">4</div>
      </div>
    </div>
  </span>


  <p>
    <strong>Content:</strong>
     <%= @ticket.content.html_safe %> 
     <!--     <%= @ticket.content %> -->
  </p>

  <% @ticket_attachments.each do |p| %>
    <a class="fancybox" rel="gallery1" href="<%= p.image_url %>">
      <img src="<%= p.image_url %>" style=" width: auto; height:100px; " alt="" />
    </a>
  <% end %><br>



  <%= link_to 'Edit', edit_ticket_path(@ticket) %> |
  <%= link_to 'Back', tickets_path %>

</div>


<script type="text/javascript">
  $(document).ready(function() {
    $("a.fancybox").fancybox();
  });
</script>